{% set version = "5.6.1" %}

package:
  name: metview
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3964985/Metview-{{ version }}-Source.tar.gz
  sha256: 5e1abf46e290911fe90cb35957c45ab61901c285b9a70e195a04d17608b86fd0
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0006-Pass-CPP-to-rpcgen.patch
    - 0007-Allow-to-build-without-Fortran-compiler.patch
    - 0009-Minimum-CMake-version-of-3.6.0.patch

build:
  number: 3
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
#    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - curl
    - eccodes
    - magics 4.1.3
    - boost >=1.70.0
    - qt >=5.9.7
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw
  run:
    - eccodes
    - magics 4.1.3
    - qt >=5.9.7
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw

test:
  commands:
    - conda inspect linkages -p $PREFIX metview
    - conda inspect objects -p $PREFIX metview  # [osx]

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache 2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: ECMWF Metview Copyright 2007-2019 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sk-ec
