{% set name = "Metview" %}
{% set version = "5.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3964985/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 6245b34909ac697f941f92ee1293f14f96c31c3919f41db5dba706de6c9d43e3
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0002-Pass-CPP-to-rpcgen.patch
    - 0003-eckit-geo-include-algorithm-header.patch
    - 0004-eckit-geo-include-memory-header.patch
    - 0006-Disable-geo-cache-check.patch

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - bison
    - cmake
    - flex
    - make
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - curl
    - shapelib
    - eccodes >=2.32.0
    - magics-metview >=4.10.0
    - qt-main
    - flex
    - glib
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas
    - libzip  # [osx]
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - xorg-libxfixes  # [linux]
    - libgl-devel                    # [linux]
  run:
    - eccodes >=2.32.0
    - magics-metview >=4.10.0
    - qt-main
    - flex
    - gdbm
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas
    - libzip  # [osx]

test:
  commands:
    - test -f $PREFIX/lib/metview-bundle/lib/libMvMacro${SHLIB_EXT}
    - test -f $PREFIX/lib/metview-bundle/bin/XSection
    - test -f $PREFIX/bin/metview

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache-2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: ECMWF Metview Copyright 2007-2022 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sandorkertesz
