{% set name = "Metview" %}
{% set version = "5.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/30048389/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 90c1224d2abf081b2ed62d914763c036ce044dfe33debd2df83e2c0b62182cdf
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0002-Pass-CPP-to-rpcgen.patch

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - curl
    - eccodes >=2.18.0
    - magics-metview >=4.4.0
    - boost
    - qt
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - xorg-libxfixes  # [linux]
  run:
    - eccodes >=2.18.0
    - magics-metview
    - qt
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas

test:
  commands:
    - conda inspect linkages -p $PREFIX metview
    - conda inspect objects -p $PREFIX metview  # [osx]

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache-2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: ECMWF Metview Copyright 2007-2020 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sandorkertesz
