{% set name = "Metview" %}
{% set version = "5.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3964985/{{ name }}-{{ version }}-Source.tar.gz
  sha256: 32219c13b0c9fd831857af1f22d790fd8c7caba512cac0b982e9ff418f2858fe
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0002-Pass-CPP-to-rpcgen.patch

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - curl
    - eccodes >=2.19.0
    - magics-metview >=4.5.1
    - qt
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas
    # See https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl
    - xorg-libxfixes  # [linux]
  run:
    - eccodes >=2.19.0
    - magics-metview >=4.5.1
    - qt
    - flex
    - bison
    - libnetcdf
    - gdbm
    - fftw
    - openblas

test:
  commands:
    - test -f $PREFIX/lib/metview-bundle/lib/libMvMacro${SHLIB_EXT}
    - test -f $PREFIX/lib/metview-bundle/bin/XSection
    - test -f $PREFIX/bin/metview

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache-2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: ECMWF Metview Copyright 2007-2020 ECMWF.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
    - iainrussell
    - sandorkertesz
