travis:
  secure:
    BINSTAR_TOKEN: h8eMwrSUV8YBz7mHWYpV6O5TMEbfOZ8OYC34JNFZS12IRqnwSRWV8AOnI2+KNEUlgWk6Z6fCCryX1BN10Vhu6tPcBjeZv+/w3xBRgEMBcV8yi7kbt2rQxKD5PvsTxGuYrLiLrB2BgESkZxPM4g3jFEX2dXDYymBskmtpJyZ5fCumCS6ETP351kx+Tz3FIVQLWZetsEso9O7lrUrb9lFjGe0vQUgmODQpdQufrpaUnjm1PR/myRi5GAwL0M65jxWga+TTZWA6Qw0RyjzMZgCjFHjbrlgILmzoaUitU0sMrAh4xdv+CAixTLEU/9syVOIctp/1SwVWFTKoQSrm/SwRuLb1OUhORqMiYfQqAzbOEGuIoO7tSQxqknkoddrkQMkV9H8eb+KSU88zTi7o3lHC2ab5LtAc4EF5PKWlX3ewZTDNZXuoy2JyAS27NbzW0RigKI681A+1nkywehuXg5MruNvxq6vfME8LoJGt/3EbfwIPGhpsQQ2YXJUl6yoo4X/hvT1cDcjEb2xbj4t8iqnSpu1f1mSU1bykd5hPIsu+fLJDCe3AW5zWq/qvtkt/D/zTavIJrF5AMPiPwV7BYXD8qJ/QCSkGi5T3FHpYVInXOzsbTHNWUimATIAHHnfhQsvK1CwDwmMYLdXA2dO+TOrOy6aIPewFlWv+/i77RAKETIA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
